name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    environment: prod
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Instalación de librerías y dependencias
        run: pip install -r requirements.txt
      - name: Correr pruebas
        run: |
          python -m coverage run -m unittest discover -s tests -v
          python -m coverage xml
      - name: Run SonarCloud Scan for ServicioFacturacion
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=rnhuni
            -Dsonar.projectKey=rnhuni_TutorialCancionesTags
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=src
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
